#!/bin/bash
device_path="/dev/ttyACM0"

while true; do
  if [ -c "$device_path" ]; then
    echo "Device found at $device_path"
    #echo pico_w
    #echo -ne "\033]0;PICO_W Debug Session\007"    
    #$HOME/.pico-sdk/openocd/0.12.0+dev/openocd -s $HOME/.pico-sdk/openocd/0.12.0+dev/scripts -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 1000"
    echo pico2_w
    echo -ne "\033]0;PICO2_W Debug Session\007"
    $HOME/.pico-sdk/openocd/0.12.0+dev/openocd -s $HOME/.pico-sdk/openocd/0.12.0+dev/scripts -f interface/cmsis-dap.cfg -f target/rp2350.cfg -c "adapter speed 1000" -c "rp2350.dap.core1 cortex_m reset_config sysresetreq"
    break
  else
    echo "Device not found at $device_path. Retrying in 5 seconds..."
    sleep 5 # Wait for 5 seconds before retrying
  fi
done

